name: validate

on: 
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: params
        run: |
          echo "commitfrom=${{ vars.commitfrom }}" >> $GITHUB_ENV
          echo "committo=${{ vars.committo }}" >> $GITHUB_ENV
          echo "auth_url=${{ secrets.auth_url }}" >> $GITHUB_ENV
          echo "destructive_file_name=destructiveChanges.xml" >> $GITHUB_ENV
          echo "deploymentuser=${{ vars.deploymentuser }}" >> $GITHUB_ENV

      - name: install sf cli
        run: |
          npm install @salesforce/cli --global
      - name: install sgd
        run: |
          echo "y" | sfdx plugins:install sfdx-git-delta@
      - name: retrieve secrets
        run: |
          echo '{
            "sfdxAuthUrl": "'"$auth_url"'"
          }' > secrets.json
          cat secrets.json
      - name: auth
        run: |
           sf org login sfdx-url --sfdx-url-file secrets.json --alias target
      - name: generate delta
        run: |
          mkdir delta
          sf sgd:source:delta --from $commitfrom --to $committo --output ./delta --generate-delta -a 65.0
          if [ ! -d "./delta/project1" ];then
            mkdir "./delta/project1"
            find "./project1" -type d -exec sh -c 'mkdir -p "./delta/project1/${1#./project1/}"' _ {} \;          
          fi
          cp project1/sfdx-project.json delta/project1
          cp delta/package/package.xml delta/project1
      - name: validate delta
        run: |
          cd project1
          sf project deploy start -x ../delta/package/package.xml --dry-run -o $deploymentuser --post-destructive-changes "../delta/destructiveChanges/$destructive_file_name"
          cd ../delta/project1
          cat "../destructiveChanges/$destructive_file_name"
          cat ../package/package.xml
          sf project deploy start -x ../package/package.xml --dry-run -o $deploymentuser --post-destructive-changes "../destructiveChanges/$destructive_file_name"
